### ISSUE TITLE
国际服ff14不适用

### ISSUE THREAD

**Issue by xu932** [DoubieV/ff14trn#2]
所有action的窗口名字都是 `最终幻想XIV`，如果用的是美服（或者国际服）则需要把窗口名字改成`FINAL FANTASY XIV`

**Comment by DoubieV** [comment]
这是个老问题了，类似的情况还有编码问题导致的窗口名乱码
早期编写时并没有考虑到窗口名带来的问题，使用了根据【窗口名】的键入
在较新的触发器中，我改用成根据【进程id】键入或使用“鲶鱼精邮差”中的sendkey方法来规避这一问题。先前的老触发器……等哪天抽空再优化吧

关于国际服适配，没有考虑过
一些触发器对日志匹配的正则中包含了中文字符，我不清楚这对国际服是否有用
我目前没有游玩国际服的打算，缺少环境获取数据和测试，有能力的自己改吧
